### ISSUE TITLE
rev5 tag?

### ISSUE THREAD

**Issue by rscohn2** [KhronosGroup/SYCL-Docs#100]
There are tags for rev6 & rev7, but not rev5. It looks like the initial commit was rev5. Is it exactly rev5? Could you tag it?

**Comment by keryell** [comment]
I thought first I forgot to push all these missing revisions on the public GitHub.
Actually they are all on the internal GitLab but the reason is that we start opening the sources of the spec just after rev5.
I pushed this branch here too, if you want to look at it: https://github.com/KhronosGroup/SYCL-Docs/tree/SYCL-1.2.1/squashed-rev-5 It is a branch, not a tag.
We did not get all the approval of all previous contributors, so the history is squashed outside of Khronos...
