### ISSUE TITLE
Allow 0-sized buffers

### ISSUE THREAD

**Issue by mfbalin** [KhronosGroup/SYCL-Docs#107]
When the user writes code, let's say the user has 100s of buffers and one of them has to have a 0 size. Since 0-sized buffers are not allowed in SYCL, existing SYCL implementations just throw an error. I don't think this is good at all. What is the harm of allowing 0-sized buffers?

**Comment by ProGTX** [comment]
There has been some discussion about this. The first problem is that zeros are not allowed in a `range`. Codeplay proposed a default constructible buffer where the user doesn't have to specify a range: https://github.com/codeplaysoftware/standards-proposals/pull/97/files. However, the decision was made that since SYCL 2020 provisional targets C++17, a user can just use `std::optional<buffer>` instead.

**Comment by fraggamuffin** [comment]
internal 542

**Comment by fraggamuffin** [comment]
https://github.com/KhronosGroup/SYCL-Docs/issues/107

**Comment by tomdeakin** [comment]
This was addressed in #192, so I think this issue can now be closed.

**Comment by zjin-lcf** [comment]
Thanks.
