### ISSUE TITLE
Meaning of SYCL

### ISSUE THREAD

**Issue by gonsolo** [KhronosGroup/SYCL-Docs#112]
I can't find the meaning of SYCL. Presumably it once meant "System OpenCL"?
I think that should be mentioned on the website, on Wikipedia and the specification.
It makes it clearer what SYCL "is".

**Comment by keryell** [comment]
There is no specific meaning, not even the one you propose since SYCL is no longer related to OpenCL since it has been generalized to various backends with SYCL 2020.
You are right, we should add this to the Wikipedia page that it has no specific meaning (actually you can do this :-) ) and add a note to the SYCL 2020 specification about it so people do not spend time asking instead of programming in SYCL.
I added this task to internal https://gitlab.khronos.org/sycl/Specification/-/issues/214

**Comment by keryell** [comment]
While updating the SYCL Wikipedia page https://en.wikipedia.org/wiki/SYCL for SYCL 2020, I have seen that you have added the answer to your question there. Great! :-)
So I guess I can close this.
Thank you.
