### ISSUE TITLE
Clarify for which types (has_)known_identity should be implemented

### ISSUE THREAD

**Issue by fknorr** [KhronosGroup/SYCL-Docs#163]
Which overloads of `sycl::reduction()` a client is allowed to call depends on whether `sycl::has_known_identity_v` is true for the argument types:

* `reduction(buffer<T>, handler &, Op, sycl::property::reduction::initialize_to_identity)` requires `has_known_identity_v<Op, T>`
* `reduction(buffer<T>, handler &, T identity, Op)` requires `!has_known_identity_v<Op, T>`

Therefore, to allow portability, the spec must state precisely for which operations and types `has_known_identity` should be provided out-of-the-box. The 2021-07-08 build talks about _standard binary operators_, but it is not clear if that is meant to apply to the function objects from section 4.17.2. Even if it does, the argument types are still not specified.

For reference, DPC++ currently implements the following pairs:

* `sycl::plus`, `sycl::multiplies` for integral and floating-point types 
* `sycl::bit_or`, `sycl::bit_and`, `sycl::bit_xor` for integral types
* `sycl::minimum`, `sycl::minimum` for integral and floating-point types, where identities are the largest/smallest representable number

IMO, the following should also be included:

* `sycl::logical_or` and `sycl::logical_and` for bool
* `sycl::plus`, `sycl::bit_{and,or,xor}`, `sycl::minimum` and `sycl::maximum` for built-in vector types

It's up for discussion whether the following should be added as well:

* `sycl::multiplies` for built-in vector types (decide if this should be a component-wise product?)

The implemented operation and argument types should either be listed exhaustively or described in terms of C++ type traits (i.e. `std::is_arithmetic_v`). For all types for which SYCL requires a specific representation, the identity values should be listed explicitly.

**Comment by keryell** [comment]
WG meeting:

- someone to specify what is the list of operators and their identities according to the various allowed types;
- clarify the spec to answer the question above about section 4.17.2;
- look at what OpenMP is doing.

**Comment by keryell** [comment]
I have just attended the ISO C++ meeting with LEWG & SG1 discussing P2300R1 `std::execution` http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2300r1.html and interestingly one of the examples is *1.3.2. Asynchronous inclusive scan* http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2300r1.html#example-async-inclusive-scan which does not use an identity element! :-)
Only the initial value is required, by just doing the computation on an existing values, starting from the initial value.
I first thought that using an identity or neutral element https://en.wikipedia.org/wiki/Identity_element or not could be seen as a *quality-of-implementation* problem.
But thinking deeper on this, requiring a neutral element is actually mathematically reducing, since it means working only on monoids (internal operation + associativity + neutral element) https://en.wikipedia.org/wiki/Monoid instead of the bigger semigroup world (internal operation + associativity) https://en.wikipedia.org/wiki/Semigroup
The associativity is required for efficient parallel execution.
@Pennycook So I suggest we get rid of the neutral element for mathematical reasons and simplify the SYCL API by removing also the need for `sycl::has_known_identity_v` if I understand the big picture correctly.

**Comment by Pennycook** [comment]
Thanks for sharing the example, @keryell.  I don't think we've considered the monoid vs semigroup angle before, and I can see how requiring an identity would limit us.  However, I don't think that SYCL 2020 actually ever _requires_ an identity -- it just (potentially) performs better if one is known.  I think removing the identity functionality would hurt the performance of many SYCL implementations so I'm against it, but if the existing reduction support is unclear we should clarify it.

I've attempted to contrast the two reduction approaches below, in an effort to show why SYCL implementations might care about whether the reduction identity value exists.  Apologies for the bad pseudocode. :)

An interface like the one used by P2300R1 is a little different to a kernel because it operates directly on a range, which allows for an implementation like this:
```c++
Iterator::value_type reduce(Iterator first, Iterator last) {
  myfirst, mylast = divide_range_across_threads(first, last);
  if (myfirst != mylast) {
    // if this parallel worker contributes to the reduction, it gets an initial value
    Iterator::value_type accum = *myfirst;
    for (Iterator it = myfirst + 1; it != mylast; ++it) {
      accum += *it;
    }
  }
  ... // combine results here somehow and return
}
```

It's possible to have situations where the number of parallel workers (e.g. threads, SIMD lanes) is larger than the range, and the implementation has to account for those when it combines the results -- some workers might not contribute to the reduction.  But since the implementation has full control over everything, it knows exactly which workers don't contribute and can handle it.

With a SYCL kernel, only the user knows whether a given work-item contributes to a reduction, because it's legal to write a kernel like this:
```c++
q.parallel_for(Range, [=](sycl::nd_item<1> it, auto& reducer) {

  // only some work-items contribute to the reduction
  if (/* some condition of it.get_global_id() */) {
    reducer += 1;
  }

});
```

If the implementation knows the identity value associated with the reduction, it can initialize the temporary reducer values associated with each work-item to the identity, and then blindly combine them all without fear.  If the implementation doesn't know the identity value, in the general case it now has to track two things per work-item: 1) the value of the reducer after executing the user-provided lambda; and 2) whether the user's lambda actually initialized the reducer to anything.

The relevant paragraph in SYCL 2020 is:

> Certain implementations of reductions can be made more efficient if the identity value associated with the reduction operator is known. For standard binary operators (e.g. plus on arithmetic types), an implementation must determine the correct identity value automatically in order to avoid performance penalties. For user-defined reduction operators, an implementation should issue a compile-time warning if the user does not provide an identity value and this is known to negatively impact performance.

The intent of this paragraph is to say that if a reduction operator has an identity, a SYCL implementation can do the fast thing.  If a reduction operator does not have an identity, a SYCL implementation must do the slow thing (e.g. initialize every reducer value to `std::optional<T>` or similar).  This can't just be a quality-of-implementation issue, because it's desirable for a user-provided reduction to be able to declare that it's compatible with the fast implementation of things.

Maybe the issue is that the text suggests an identity value is a natural thing for all reduction operators to have, rather than something that a reduction operator _might_ have?  Do you think rewriting things to adjust this subtle distinction would be clearer?

**Comment by keryell** [comment]
Yes you are right, it allows optimizations in the case of the explicit spacial execution.
Perhaps
> if the identity value associated with the reduction operator is known.

could be rephrased as
> if an identity value does exist for the reduction operator and is known by the implementation.

**Comment by Pennycook** [comment]
I agree that's clearer.  I'll rephrase things over on https://github.com/KhronosGroup/SYCL-Docs/pull/172.

**Comment by fknorr** [comment]
I propose the following additions to the spec. The wording might need to be less restrictive depending on the outcome of #172.

## 4.9.2. Reduction variables:

For all of the following partial specializations, `known_identity` exists and `has_known_identity` is true if specified in the table below. An implementation must not define additional identities.

```c++
template<typename T, typename U> struct known_identity<op<T>, U>;
template<typename T, int N, typename U> struct known_identity<op<vec<T, N>>, U>;
template<typename T> struct known_identity<op<void>, T>;
template<typename T, int N> struct known_identity<op<void>, vec<T, N>>;
```

| Operator            | Enabled if                                                                       | Identity in each Component            |
|---------------------|----------------------------------------------------------------------------------|---------------------------------------|
| `sycl::plus`        | `std::is_arithmetic_v<T>`                                                        | `T{}`                                 |
| `sycl::multiplies`  | `std::is_arithmetic_v<T>`                                                        | `T{1}`                                |
| `sycl::bit_and`     | `std::is_integral_v<T>`                                                          | `~T{}`                                |
| `sycl::bit_or`      | `std::is_integral_v<T>`                                                          | `T{}`                                 |
| `sycl::bit_xor`     | `std::is_integral_v<T>`                                                          | `T{}`                                 |
| `sycl::logical_and` | `std::is_same_v<std::remove_cv_t<T>, bool>`                                      | `true`                                |
| `sycl::logical_or`  | `std::is_same_v<std::remove_cv_t<T>, bool>`                                      | `false`                               |
| `sycl::minimum`     | `std::is_integral_v<T>`                                                          | `std::numeric_limits<T>::max()`       |
| `sycl::minimum`     | `std::is_floating_point<T> \|\| std::is_same_v<std::remove_cv_t<T>, sycl::half>` | `std::numeric_limits<T>::infinity()`  |
| `sycl::maximum`     | `std::is_integral_v<T>`                                                          | `std::numeric_limits<T>::min()`       |
| `sycl::maximum`     | `std::is_floating_point<T> \|\| std::is_same_v<std::remove_cv_t<T>, sycl::half>` | `-std::numeric_limits<T>::infinity()` |

## C.9.1. Half precision floating-point

`std::numeric_limits<half>` must be implemented to expose the correct characteristics of the `half` type.

**Comment by Pennycook** [comment]
> An implementation must not define additional identities.

I think this is too restrictive, and contradicts the section about the extension mechanism.    An implementation should be free to define additional identities (e.g. because it may introduce new types).

**Comment by fraggamuffin** [comment]
Table is Ok, just removed these wordings:
An implementation must not define additional identities.
For identities that are known, it says what that identity is.

**Comment by fraggamuffin** [comment]
can override identity if have known identity.

**Comment by Pennycook** [comment]
Continuing discussion with @psalz about what it means for a reduction to be launched when the identity is not known or not provided. The parts of the specification that I think are relevant are:

From [Section 4.9.2, "Reduction variables"](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:reduction):

> Certain implementations of reductions can be made more efficient if the reduction operator has an identity value and this value is known to the implementation. For standard binary operators (e.g. plus on arithmetic types), an implementation can determine the correct identity value automatically in order to avoid performance penalties.
>
> If an implementation can identify an identity value for a given combination of accumulator type and function object type, the value is defined as a member of the known_identity trait class. Whether this member value exists can be tested using the has_known_identity trait class.

The flip-side of the first paragraph is that not all reduction implementations require the reduction operator to have an identity value, or for that value to be known to the implementation. If you think it would be clearer, perhaps we could rephrase this first sentence as:

> Reduction operators are not required to have an identity value, but some SYCL implementations may optimize for the case where a reduction operator has an identity value and this value is known to the implementation. For standard binary operators...

Then, from [Section 4.9.2.1, "`reduction` interface"](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#reduction-interface):

> An implementation may use an unspecified number of temporary variables inside of any reducer objects it creates. If an identity value is supplied to a reduction, an implementation will use that value to initialize any such temporary variables.
>
> Since the number of temporary variables is unspecified, supplying an identity value different to the identity value associated with the reduction operator may lead to unexpected results.
>
> The initial value of the reduction variable is included in the reduction operation, unless the property::reduction::initialize_to_identity property was specified when the reduction interface was invoked.

So, it's definitely problematic if the user provides the _wrong_ identity value for a given reduction operator, but nothing here says that the user is required to specify an identity.

The part about initializing temporary variables is why I made reference to `std::optional`. If an identity is unknown, an implementation is likely to either: a) avoid temporary variables completely, by updating the original reduction variable; or b) keep track of which work-items call `combine()` and thus contribute to the reduction.

For user-defined operators, an implementation must support a reduction without an identity, since nothing mentions throwing an error in that case.

**Comment by psalz** [comment]
Thanks for the writeup @Pennycook, it's clear to me now.

> If you think it would be clearer, perhaps we could rephrase this first sentence [...]

No, I think it's fine the way it is. Although should it maybe say

> For standard binary operators (e.g. plus on arithmetic types), an implementation ~can~ may be able to determine

because whether an identity is known not only depends on the operator, but also the operand type (i.e., `AccumulatorT`)?
