### ISSUE TITLE
[Group Algorithms] Clarifications on memory aliasing

### ISSUE THREAD

**Issue by Michoumichmich** [KhronosGroup/SYCL-Docs#191]
Hello, 

I think that the spec is unclear on `joint_inclusive_scan` and `joint_exclusive_scan`: are the memory pointers allowed to alias each-other? Or they are `restrict`? 

Knowing that would allow to write in-place scans and avoid having to use a potentially useless buffer (and so increase performance). I think that we should be able to allow the pointers to alias each-other. 

Some implementations already write `joint_inclusive_scan` as a loop over `inclusive_scan_over_group ` so it wouldn't change much.

Best, 
Michel

**Comment by Pennycook** [comment]
I think this is covered by the following, from [4.17.4 Group algorithms library](https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:algorithms):

> Any restrictions from the standard algorithms library apply. Some of the functions in the SYCL algorithms library introduce additional restrictions in order to maximize portability across different devices and to minimize the chances of encountering unexpected behavior.

The C++ description of these functions doesn't include a restriction that the memory pointers may not alias (in fact, it says [the opposite](http://eel.is/c++draft/inclusive.scan#9)); since the SYCL specification doesn't introduce this restriction either, my reading of the spec is that they _may_ alias.

I agree it could be clearer, though.  I wouldn't be opposed to adding something like a:

> _Remarks_: _result_ may be equal to _first_.

...to the description of each algorithm, if people agree with my reading.

**Comment by Michoumichmich** [comment]
Hello @Pennycook, 
Thanks a lot for yout response and dorry for responding with that much delay (back to studies). 
I missed that remark while checking the draft. 
So, as it's explicitly stated in the C++ standard, is it fine if I open the PR ?
