### ISSUE TITLE
Typed USM Deallocation Functions (sycl::free)

### ISSUE THREAD

**Issue by pkeir** [KhronosGroup/SYCL-Docs#203]
Many of the USM Memory Allocation Functions (function templates) return a typed pointer. But the two `sycl::free` functions only accept a void pointer. It is likely that a form of C++ `operator new` will/could be used by an implementation of the USM memory allocation functions, but deleting `void*` (by using a `operator delete`) is undefined in C++. Could a typed `sycl::free` be specified instead?

Section 4.8.3.6
Table 104. USM Deallocation Functions

```cpp
void sycl::free(void* ptr, sycl::context& syclContext);
void sycl::free(void* ptr, sycl::queue& syclQueue);
```

...would become:

```cpp
template <typename T>
void sycl::free(T* ptr, sycl::context& syclContext);
template <typename T>
void sycl::free(T* ptr, sycl::queue& syclQueue);
```

**Comment by gmlueck** [comment]
> It is likely that a form of C++ operator new will/could be used by an implementation of the USM memory allocation functions

I think this is not true.  The USM allocations that return a typed pointer return a pointer to *uninitialized* memory.  Therefore, they would not be implemented by calling `operator new`.

> Could a typed sycl::free be specified instead?

This is possible, but I'm not sure how useful it is.  Since the allocation functions don't call the object's constructor, the `free` function shouldn't call the destructor.  Thus, even if we added versions of `sycl::free()` that took a typed pointer, they would do the same thing as the versions that take a `void *`.

**Comment by nliber** [comment]
Even if we decided to add a call to invoke the destructor and then deallocate the memory, I'd be strongly against naming that `free` for the reasons @gmlueck has already mentioned.

Additionally, in such a call I think we'd have to say something about what happens if the `T` destructor throws, as well as what happens if you pass a `const` or `volatile` pointer (that could easily happen with type deduction).

**Comment by fraggamuffin** [comment]
Can you expand further on why you want this? is it to support nvc++ malloc/free in motorSYCL or something else? can using cudaMalloc_managed work?

**Comment by pkeir** [comment]
I assume I was looking for a typed/template version of `sycl::free`, but the point I made about implementing this using `delete` is totally bogus. For the sake of symmetry, I could imagine specifying typed versions of `sycl::free` *in addition* to the `void*` versions, but not instead (as I'd suggested earlier).
