### ISSUE TITLE
USM allocation behaviour when requesting memory of zero size

### ISSUE THREAD

**Issue by jakub-homola** [KhronosGroup/SYCL-Docs#355]
Hi,

I could not find any information in the [SYCL spec](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#sec:usm) about how the USM allocations functions (including the usm_allocator) should behave when requested to allocate a memory of zero size.

For buffers it is explicitly stated that zero-sized buffers are permitted. However, this information seems missing for USM.

Testing with DPC++, `usm_allocator::allocate` throws a `sycl::_V1::memory_allocation_error` exception (for both host and shared specializations), while `malloc_shared` performs fine and returns a nullptr.

**Comment by gmlueck** [comment]
I agree that we should clarify the behavior of the USM "malloc" functions, using similar language as the C/C++ specification.  This is what [cppreference](https://en.cppreference.com/w/cpp/memory/c/malloc) says:

> If size is zero, the behavior is implementation defined (null pointer may be returned, or some non-null pointer may be returned that may not be used to access storage, but has to be passed to `std::free`.

I think the SYCL spec does not need to further clarify the behavior of `usm_allocator::allocate` because we already say that `usm_allocator` follows the C++ named required _Allocator_:

> SYCL defines an allocator class named `usm_allocator` that satisfies the C++ named requirement `Allocator`.

([Section 4.8.3.1](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_c_allocator_interface) C++ allocator interface)

I believe the C++ standard says that the `allocate` function does not throw when size is zero, so I think the DPC++ implementation is wrong.

**Comment by gmlueck** [comment]
I created an internal bug report against DPC++ reporting this issue with `usm_allocator::allocate`, which contains a link to this issue.

**Comment by gmlueck** [comment]
The text of the C++ standard seemed a little clearer to me.  It lists specific conditions for throwing an exception:

* If the requested allocation is too big (the spec has a more formal definition of this)
* If the system is unable to allocate memory

Since the spec does not list "size 0" as a condition for throwing an exception, I think we need to assume that an implementation should not throw for this reason.

**Comment by jakub-homola** [comment]
Okay, sorry, I did not read the full text of the standard. But that makes sense. Thanks for clearing that up for me.
