### ISSUE TITLE
Is any plan to develop and merge intel dpct library like cuda_runtime_api.h?

### ISSUE THREAD

**Issue by alanzhai219** [KhronosGroup/SYCL-Docs#578]
As we all know that sycl/sycl.hpp is not very friendly if we compare it with cuda_runtime_api.h. We always code a long long function to get some results, right? for example

cuda: warpSize
sycl: it.get_sub_group().get_local_range().get(0) Do you think it looks elegant? It looks very obscure. We should avoid hard code in the design but sycl spec has lots of hard code 0/1/2. So I create some macro to replace it. https://github.com/alanzhai219/sycl_help_header/blob/main/sycl_help_api.hpp
In order to help developers understand and develop the sycl quickly, why not design a runtime level api like nvidia's cuda_runtime_api does?
Looks dpct has implemented some of these esay-used api but not enough.
How do you think about it?

**Comment by TApplencourt** [comment]
Hi,

I think it's a good idea. 
The SYCL specification allows for the creation of extensions. A more `c` style API can be part of it.

For example, Intel worked on a more "free-function" style approach for some object (https://github.com/intel/llvm/blob/a1e38b5a92852b34bd3b6389175770eb822db7b9/sycl/doc/extensions/proposed/sycl_ext_oneapi_free_function_queries.asciidoc)

**Comment by illuhad** [comment]
> cuda: warpSize
> sycl: it.get_sub_group().get_local_range().get(0) 

I think this comparison only holds for simple cases. One you have obtained the subgroup in SYCL, you can do a lot more with it than just query the subgroup size, for example get the local id within the subgroup, or get the id of the subgroup within the work group. In CUDA, you will have to do these calculations manually and at that point the CUDA code would be both less readable and likely also longer than the equivalent SYCL code.

I'm skeptical that this will be beneficial for any non-trivial code.

As @TApplencourt there are some efforts to investigate alternative APIs. But I can't see it boiling down to CUDA.

**Comment by alanzhai219** [comment]
@illuhad 
To be honest, I only agree with part of your views.
- It might be possible to quickly query the subgroup size or thread ID in SYCL, but the complex and obscure API function names make it difficult for developers to distinguish and understand them. Especially for a CUDA developer, if SYCL's usability is only 60%, why would they spend a lot of effort abandoning the 100% efficient CUDA programming language?
- Based on past experience, thread computation in CUDA is a very lightweight multiply-add formula. I don't believe this will lead to a performance bottleneck. In other words, CUDA could completely introduce a new API, which wouldn't be difficult for CUDA. But why haven't they done so? I think it's because CUDA doesn't consider this to be a performance bottleneck.

Of course, This is just my personal suggestion. As a developer, I cannot influence the iteration and roadmap of the programming language itself.

**Comment by illuhad** [comment]
> It might be possible to quickly query the subgroup size or thread ID in SYCL, but the complex and obscure API function names make it difficult for developers to distinguish and understand them

SYCL 2020 is very consistent about the naming and meaning of API functions to query the parallel iteration space. Sure, the SYCL conventions are different from CUDA, but if you are migrating from CUDA, then there are already dedicated tools available.

The SYCL API most certainly is not more obscure than the actual calculations it needs to carry out. Subgroup calculations e.g. in a 3D kernel is in general not a trivial operation and may or may not involve compiler builtins. See e.g. https://github.com/AdaptiveCpp/AdaptiveCpp/blob/develop/src/libkernel/sscp/ptx/subgroup.cpp

The reason why there are abstractions for these things in SYCL is that the implementation in general knows better how to do these things. This is in particular true because SYCL is much, much more general than CUDA and supports a lot of different backends and hardware, which may behave differently and handle these things differently.

The fact that SYCL exposes APIs for this contributes to allowing SYCL to run efficiently on many device types. Some degree of abstraction is necessary for performance portability.

For the same reason, e.g. OpenCL has `get_global_id()` functions as well which mirror what SYCL is doing.

> Based on past experience, thread computation in CUDA is a very lightweight multiply-add formula. I don't believe this will lead to a performance bottleneck. In other words, CUDA could completely introduce a new API, which wouldn't be difficult for CUDA. But why haven't they done so? I think it's because CUDA doesn't consider this to be a performance bottleneck.

I find the notion "if something is not in CUDA, it must be because there is no need for it" highly questionable. I know that there are multiple things in CUDA that NVIDIA would like to backtrack if they could. CUDA is one of the earliest heterogeneous APIs and we have learned some things since then.
Even if we just look at NVIDIA GPUs and ignore the portability aspect for a moment, while it's true that thread id calculation "just" involves addition and multiplication, whether that is lightweight actually depends on what the rest of the kernel is doing. If the kernel does a lot of complex other things, then it will probably not matter. For very simple kernels, it can matter.

>  the 100% efficient CUDA programming language?

this assertion is most certainly not true. There are cases where SYCL implementations outperform CUDA. There are cases where other models outperform CUDA. The efficiency of CUDA on non-NVIDIA hardware is 0%.

> Of course, This is just my personal suggestion. As a developer, I cannot influence the iteration and roadmap of the programming language itself.

Of course you can, you are trying now :) It's just that some people with more experience with SYCL may disagree with your arguments :) I'm just trying to explain to you that SYCL designers are not dumb either and there might be a reason that things are the way they are.

**Comment by alanzhai219** [comment]
@illuhad I see. But I mean the programming model and API should be simpler, which can attract developers and extend the ecosystem.

**Comment by alanzhai219** [comment]
@illuhad 
I see. 
Your point is on performance while my point is on programming experience.
Performance and ease of use should not be opposites. Designers should take both into account, maintaining performance while making the programming model and interfaces as simple as possible. Only in this way can developers be attracted and the ecosystem be expanded.
On the contrary, insisting on performance first and neglecting the programming experience will discourage developers.
How about providing two levels API like cuda_runtime_api.h and cuda_driver_api.h. runtime_api is for easy-use while driver_api is for performance tuning. This may be able to take into account both novice developers and advanced developers at the same time.

**Comment by illuhad** [comment]
> Performance and ease of use should not be opposites. Designers should take both into account, maintaining performance while making the programming model and interfaces as simple as possible. Only in this way can developers be attracted and the ecosystem be expanded.

Oh, I agree.

> On the contrary, insisting on performance first and neglecting the programming experience will discourage developers.

Of course. My position is not that we should prioritize performance at all costs.

My first post was actually about programmer experience. I went more in the performance direction because I understood your second post (https://github.com/KhronosGroup/SYCL-Docs/issues/578#issuecomment-2228429726 ) to be invoking performance-related arguments.

My original point was that actually in most non-trivial programs, the SYCL API may not be as clumsy as you construct it to be in a two-line example, and that equivalent CUDA will be much, much more complicated. So I'm skeptical about the claim that CUDA is a simpler model.

For example, in your subgroup example:
```c++
// In a real-world program we would obtain the subgroup object once:
auto sg = it.get_sub_group();
// In a real-world program chances are that we actually need more than just one property of the subgroup:
// Number of work items in the calling subgroup
unsigned sg_size = sg.get_local_linear_range();
// Id of the calling work item within the subgroup
unsigned my_id_in_sg = sg.get_local_linear_id();
// Id of the subgroup within the work group
unsigned sg_id = sg.get_group_linear_id();
```
An equivalent CUDA code is going to be far, far longer. Try it for a 3D kernel and see for yourself :-)

Now that does not mean that we shouldn't look at cases where we can simplify things. But CUDA most certainly is not the epitome of simplicity.

**Comment by alanzhai219** [comment]
I would like to agree with you. Let's move forward in SYCL ecosystem.
