### ISSUE TITLE
Clarification for aligned allocations: Is count % alignment != 0 valid?

### ISSUE THREAD

**Issue by will-saunders-ukaea** [KhronosGroup/SYCL-Docs#683]
C++ `aligned_alloc` has the stipulation that "The size parameter must be an integral multiple of alignment." [1]. Does the same restriction apply to `aligned_alloc_host`, `aligned_alloc_device` and `aligned_alloc_shared`? Apologies if this is in the specification and I am missing it.

[1] https://en.cppreference.com/w/c/memory/aligned_alloc

**Comment by gmlueck** [comment]
Currently, the spec just says:

> these functions return nullptr if the alignment is not supported by the implementation

(https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_usm_allocations)

I think we used this wording because it is the same as the wording for `std::aligned_alloc`.  The ISO C++ specification simply states that `std::aligned_alloc` has the semantics specified in ISO C.  The ISO C spec says:

> The aligned_alloc function allocates space for an object whose alignment is specified by
> alignment, whose size is specified by size, and whose representation is indeterminate. If the
> value of alignment is not a valid alignment supported by the implementation the function shall fail
> by returning a null pointer.

(https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3047.pdf)

I think the cppreference wording is wrong here.  It looks like the wording was corrected in [DR460](https://open-std.org/JTC1/SC22/WG14/www/docs/summary.htm#dr_460), but that correction did not make its way to cppreference.

**Comment by will-saunders-ukaea** [comment]
Great, thanks for the help!
