### ISSUE TITLE
Create placeholder accessors without buffer

### ISSUE THREAD

**Issue by psalz** [KhronosGroup/SYCL-Docs#92]
I'm facing a situation were I need to create a placeholder accessor without knowing the buffer the accessor will operate on. While thinking about potential solutions to this (as it is not possible in SYCL 1.2.1 Revision 6), I found that apparently ComputeCpp used to support this in an extension, where `cl::sycl::handler::require()` would optionally also take a buffer as a second argument, thus binding the provided accessor to that buffer. You [can see it in action here](https://github.com/codeplaysoftware/computecpp-sdk/blob/425ad3b03d79d647fdca51dd11ff9893ea7b7337/samples/placeholder-accessors.cpp). This extension has since been deprecated, unfortunately.

Are there any plans to introduce such functionality into future versions of SYCL?

**Comment by ProGTX** [comment]
Hi,

that particular extension proved a bit problematic when it came to modifying accessor state. Instead, Codeplay has put forth two new proposals:
1. [Accessor as Container](https://github.com/codeplaysoftware/standards-proposals/pull/124/files) defines, among other things, a default accessor constructor.
2. [Default placeholder](https://github.com/codeplaysoftware/standards-proposals/pull/122/files) deprecates the `accessor::placeholder` and introduces new functionality to `require`

I believe those two proposals together would give you the desired functionality. Though instead of binding an accessor by calling `require` you construct a new accessor and use the assignment operator. This ensures that `require` doesn't have to change accessor state, it simply registers the accessor with the command group.

**Comment by psalz** [comment]
I see. I already suspected that mutating the accessor state could lead to some headaches.

I like these new proposals a lot, using the assignment operator is a neat idea! I'm actually not that interested in the original use case for placeholders (i.e., creating some functors that operate on accessors before the queue or CGF exists). What I *really* want is a default constructor for accessors. So if you can get these proposals through, I'll be very happy ;-).

**Comment by psalz** [comment]
Closing as this has effectively been addressed in SYCL 2020.
